version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: petto
      POSTGRES_USER: petto
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
