# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: elixir:1.4.2
        environment:
          MIX_ENV: test

      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: petto
          POSTGRES_PASSWORD: petto

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
  # deploy:
  #   machine:
  #     enabled: true
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run:
  #         name: Setup WeDeploy CLI
  #         command: bash .circleci/setup_cli.sh

  #     - run:
  #         command: |
  #           we remote set xyz wedeploy.xyz
  #           echo $AUTH_TOKEN | we login -r xyz
  #           we deploy -p petto -r xyz

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
